/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.extensions.scheduler;

import io.agentscope.core.message.Msg;
import io.agentscope.extensions.scheduler.config.AgentConfig;
import io.agentscope.extensions.scheduler.config.ScheduleConfig;
import reactor.core.publisher.Mono;

/**
 * Interface representing a scheduled agent task.
 *
 * <p>This interface defines the core operations for managing and controlling scheduled agent tasks.
 * It provides a clean separation between task scheduling concerns and agent execution logic.
 *
 * <p><b>Design Principles:</b>
 * <ul>
 *   <li><b>Single Responsibility</b> - Focuses solely on task lifecycle management</li>
 *   <li><b>Interface Segregation</b> - Minimal interface with only essential operations</li>
 *   <li><b>Framework Agnostic</b> - Can be implemented with any scheduling backend</li>
 * </ul>
 *
 * <p><b>Usage Example:</b>
 * <pre>{@code
 * // Schedule an agent task
 * AgentConfig config = AgentConfig.builder()
 *     .name("MyAgent")
 *     .model(myModel)
 *     .build();
 *
 * ScheduleAgentTask task = scheduler.schedule(config, scheduleConfig);
 *
 * // Control the task
 * String taskId = task.getId();
 * String taskName = task.getName();
 *
 * // Manually trigger execution
 * task.run();
 *
 * // Cancel the task
 * task.cancel();
 * }</pre>
 *
 * @see AgentScheduler
 * @see AgentConfig
 * @see ScheduleConfig
 */
public interface ScheduleAgentTask<T> {

    /**
     * Get the unique identifier of this scheduled task.
     *
     * <p>The ID is typically generated by the scheduler implementation and remains
     * constant throughout the task's lifecycle. It can be used to uniquely identify
     * and retrieve the task from the scheduler.
     *
     * @return The unique task identifier
     */
    String getId();

    /**
     * Get the name of this scheduled task.
     *
     * <p>The name is derived from the agent configuration and is used for
     * human-readable identification. It may not be unique if multiple tasks
     * are created from the same agent configuration.
     *
     * @return The task name
     */
    String getName();

    /**
     * Execute the scheduled task immediately.
     *
     * <p>This method triggers a manual execution of the task outside of its
     * regular schedule. The execution will:
     * <ul>
     *   <li>Create a fresh agent instance using the configured AgentConfig</li>
     *   <li>Execute the agent's logic with the provided input messages</li>
     *   <li>Track execution metrics (execution count, etc.)</li>
     *   <li>Return the agent's response as a Mono</li>
     * </ul>
     *
     * <p><b>Thread Safety:</b> Implementations should ensure this method is thread-safe
     * and can be called concurrently with scheduled executions.
     *
     * @param msgs The input messages to pass to the agent (optional, can be empty)
     * @return A Mono that emits the agent's response message when execution completes
     * @throws IllegalStateException if the task has been cancelled
     * @throws RuntimeException if the execution fails
     */
    Mono<T> run(Msg... msgs);

    /**
     * Cancel this scheduled task permanently.
     *
     * <p>After cancellation:
     * <ul>
     *   <li>No further scheduled executions will occur</li>
     *   <li>The task will be removed from the scheduler</li>
     *   <li>Calling {@link #run(Msg...)} may throw an IllegalStateException</li>
     *   <li>This operation is typically irreversible</li>
     * </ul>
     *
     * <p>If the task is currently executing, the behavior depends on the scheduler
     * implementation - it may wait for completion or attempt to interrupt execution.
     *
     * <p>Calling cancel on an already cancelled task should be idempotent (no-op).
     */
    void cancel();
}
