/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.rag.integration.haystack;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.core.type.TypeReference;
import io.agentscope.core.rag.integration.haystack.model.HayStackResponse;
import io.agentscope.core.util.JsonUtils;
import java.io.IOException;
import java.time.Duration;
import java.util.Map;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Unit test for HayStackClient request generation.
 *
 * <p>This test verifies that the request body generated by HayStackClient
 * conforms to the expected custom HayStack RAG REST API contract.
 */
class HayStackClientRequestTest {

    private MockWebServer mockWebServer;

    @BeforeEach
    void setUp() throws IOException {
        mockWebServer = new MockWebServer();
        mockWebServer.start();
    }

    @AfterEach
    void tearDown() throws IOException {
        mockWebServer.shutdown();
    }

    private MockResponse createSuccessResponse() {
        return new MockResponse()
                .setResponseCode(200)
                .setHeader("Content-Type", "application/json")
                .setBody(
                        """
                        {
                          "code": 0,
                          "documents": []
                        }
                        """);
    }

    private Map<String, Object> parseAndPrintRequest(RecordedRequest request) throws Exception {
        String body = request.getBody().readUtf8();

        System.out.println("\n" + "=".repeat(70));
        System.out.println("HayStack API Request Validation");
        System.out.println("=".repeat(70));
        System.out.println("Method: " + request.getMethod());
        System.out.println("Path: " + request.getPath());
        System.out.println("-".repeat(70));
        System.out.println("Headers:");
        request.getHeaders()
                .names()
                .forEach(name -> System.out.println("  " + name + ": " + request.getHeader(name)));
        System.out.println("-".repeat(70));

        Map<String, Object> parsed =
                JsonUtils.getJsonCodec().fromJson(body, new TypeReference<>() {});
        String prettyJson = JsonUtils.getJsonCodec().toPrettyJson(parsed);
        System.out.println("Request Body:");
        System.out.println(prettyJson);
        System.out.println("=".repeat(70) + "\n");

        return parsed;
    }

    @Test
    void shouldGenerateCompleteHayStackRequest() throws Exception {
        mockWebServer.enqueue(createSuccessResponse());

        // === Build filters ===
        Map<String, Object> filters =
                Map.of(
                        "author", "Toby",
                        "category", "AI",
                        "year", Map.of("$gte", 2024));

        // === Build full config ===
        HayStackConfig config =
                HayStackConfig.builder()
                        .baseUrl(mockWebServer.url("/retrieve").toString())
                        .topK(10)
                        .scaleScore(true)
                        .returnEmbedding(true)
                        .scoreThreshold(0.3d)
                        .groupBy("source_id")
                        .groupSize(5)
                        .windowSize(2)
                        .filters(filters)
                        .timeout(Duration.ofSeconds(60))
                        .maxRetries(2)
                        .addCustomHeader("X-Request-ID", "haystack-test-123")
                        .addCustomHeader("X-Trace-ID", "trace-456")
                        .build();

        HayStackClient client = new HayStackClient(config);

        // === Execute ===
        HayStackResponse response = client.retrieve("What is Haystack RAG?", null, null).block();

        assertNotNull(response);

        // === Capture request ===
        RecordedRequest request = mockWebServer.takeRequest();
        Map<String, Object> body = parseAndPrintRequest(request);

        // === Verify HTTP ===
        assertEquals("POST", request.getMethod());
        assertEquals("/retrieve", request.getPath());
        assertTrue(request.getHeader("Content-Type").contains("application/json"));
        assertEquals("haystack-test-123", request.getHeader("X-Request-ID"));
        assertEquals("trace-456", request.getHeader("X-Trace-ID"));

        // === Verify Required Field ===
        assertEquals("What is Haystack RAG?", body.get("query"));

        // === Verify Retrieval Parameters ===
        assertEquals(10, body.get("top_k"));
        assertEquals(true, body.get("scale_score"));
        assertEquals(true, body.get("return_embedding"));
        assertEquals(0.3, ((Number) body.get("score_threshold")).doubleValue());

        // === Verify Grouping ===
        assertEquals("source_id", body.get("group_by"));
        assertEquals(5, body.get("group_size"));

        // === Verify Window ===
        assertEquals(2, body.get("window_size"));

        // === Verify Filters ===
        @SuppressWarnings("unchecked")
        Map<String, Object> actualFilters = (Map<String, Object>) body.get("filters");
        assertNotNull(actualFilters);
        assertEquals("Toby", actualFilters.get("author"));
        assertEquals("AI", actualFilters.get("category"));

        System.out.println("✅ HayStack request validated successfully!");
    }
}
